-- CreateTable
CREATE TABLE `UserData` (
    `UUID_UD` VARCHAR(191) NOT NULL,
    `Name_UD` VARCHAR(191) NOT NULL,
    `Email_UD` VARCHAR(191) NOT NULL,
    `Password_UD` VARCHAR(191) NOT NULL,
    `Role_UD` ENUM('USER', 'ADMIN', 'SUPERADMIN') NOT NULL,
    `LoggedAt_UD` DATETIME(3) NULL,
    `UpdatedAt_UD` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CreatedAt_UD` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`UUID_UD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
